services:
  # Backend API service
  - type: web
    name: mock-interview-api
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: mock-interview-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  # Frontend service
  - type: web
    name: mock-interview-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://mock-interview-api.onrender.com

# Database
databases:
  - name: mock-interview-db
    databaseName: mock-interview
    plan: free